version: '3.8'

services:
  web:
    build: .
    image: exif-extractor
    container_name: exif-extractor-web
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/uploads
    volumes:
      - uploads:/app/uploads
      - ./templates:/app/templates  # Mount templates for easy updates
      - ./static:/app/static  # Mount static files
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Uncomment if you need Redis for rate limiting
  # redis:
  #   image: redis:alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data

volumes:
  uploads:
  # redis_data:
